[project]
enable_telemetry = false
user_env = []
session_timeout = 3600
cache = false
allow_origins = ["*"]

[features]
unsafe_allow_html = false
latex = false
auto_tag_thread = true
edit_message = true

[features.spontaneous_file_upload]
    enabled = true
    accept = ["*/*"]
    max_files = 20
    max_size_mb = 500

[features.audio]
    min_decibels = -45
    initial_silence_timeout = 3000
    silence_timeout = 1500
    max_duration = 15000
    chunk_duration = 1000
    sample_rate = 44100

[UI]
name = "УниКредит Асистент"
description = "AI асистент на УниКредит Булбанк"
default_collapse_content = true
cot = "full"

[UI.theme]
    default = "light"

[UI.theme.light]
    background = "#FFFFFF"
    paper = "#F5F5F5"

    [UI.theme.light.primary]
        main = "#E2001A"
        dark = "#B30015"
        light = "#FF4D61"
    [UI.theme.light.text]
        primary = "#000000"
        secondary = "#616161"

[UI.theme.dark]
    background = "#1E1E1E"
    paper = "#2D2D2D"

    [UI.theme.dark.primary]
        main = "#E2001A"
        dark = "#B30015"
        light = "#FF4D61"
    [UI.theme.dark.text]
        primary = "#FFFFFF"
        secondary = "#BDBDBD"

[meta]
generated_by = "1.3.2"

custom_css = '../public/elastic.css'